image: archlinux
packages:
  - python-poetry
sources:
  - https://git.sr.ht/~alanorth/csv-metadata-quality
tasks:
  - setup: |
      cd csv-metadata-quality
      poetry install --dev
  - pytest: |
      cd csv-metadata-quality
      poetry run pytest
  - testcli: |
      cd csv-metadata-quality
      poetry run pip install .
      poetry run csv-metadata-quality -i data/test.csv -o /tmp/test.csv -e -u --agrovoc-fields dc.subject,cg.coverage.country
