image: archlinux
packages:
  - python-pipenv
sources:
  - https://git.sr.ht/~alanorth/csv-metadata-quality
tasks:
  - setup: |
      cd csv-metadata-quality
      pipenv install --dev
  - pytest: |
      cd csv-metadata-quality
      pipenv run pytest
  - testcli: |
      cd csv-metadata-quality
      pipenv run pip install .
      pipenv run csv-metadata-quality -i data/test.csv -o /tmp/test.csv -u --agrovoc-fields dc.subject,cg.coverage.country
environment:
  PIPENV_NOSPIN: 'True'
  PIPENV_HIDE_EMOJIS: 'True'
