image: archlinux
packages:
  - python-pipenv
sources:
  - https://git.sr.ht/~alanorth/csv-metadata-quality
tasks:
  - setup: |
      cd csv-metadata-quality
      pipenv install --dev
  - pytest: |
      cd csv-metadata-quality
      pipenv run pytest
  - test: |
      cd csv-metadata-quality
      pipenv shell pip install .
      pipenv shell csv-metadata-quality -i data/test.csv -o /dev/null -u
environment:
  PIPENV_NOSPIN: 'True'
  PIPENV_HIDE_EMOJIS: 'True'
