image: archlinux
packages:
  - python-pipenv
sources:
  - https://git.sr.ht/~alanorth/csv-metadata-quality
tasks:
  - setup: |
      pipenv install
environment:
  PIPENV_NOSPIN: 'True'
  PIPENV_HIDE_EMOJIS: 'True'
