---
kind: pipeline
type: docker
name: python39

steps:
- name: test
  image: python:3.9-slim
  commands:
  - id
  - python -V
  - apt update && apt install -y gcc g++ libicu-dev pkg-config
  - pip install -r requirements-dev.txt
  - pytest
  - python setup.py install
  - csv-metadata-quality -i data/test.csv -o /tmp/test.csv -e -u --agrovoc-fields dc.subject,cg.coverage.country

---
kind: pipeline
type: docker
name: python38

steps:
- name: test
  image: python:3.8-slim
  commands:
  - id
  - python -V
  - apt update && apt install -y gcc g++ libicu-dev pkg-config
  - pip install -r requirements-dev.txt
  - pytest
  - python setup.py install
  - csv-metadata-quality -i data/test.csv -o /tmp/test.csv -e -u --agrovoc-fields dc.subject,cg.coverage.country

---
kind: pipeline
type: docker
name: python37

steps:
- name: test
  image: python:3.7-slim
  commands:
  - id
  - python -V
  - apt update && apt install -y gcc g++ libicu-dev pkg-config
  - pip install -r requirements-dev.txt
  - pytest
  - python setup.py install
  - csv-metadata-quality -i data/test.csv -o /tmp/test.csv -e -u --agrovoc-fields dc.subject,cg.coverage.country

# vim: ts=2 sw=2 et
