---
kind: pipeline
type: docker
name: python311

steps:
- name: test
  image: python:3.11-slim
  commands:
  - id
  - python -V
  - apt update && apt install -y gcc g++ libicu-dev pkg-config git
  - python -m pip install poetry
  - poetry install
  - poetry run pytest
  # Basic test
  - poetry run csv-metadata-quality -i data/test.csv -o /tmp/test.csv
  # Basic test with unsafe fixes
  - poetry run csv-metadata-quality -i data/test.csv -o /tmp/test.csv -u
  # Geography test
  - poetry run csv-metadata-quality -i data/test-geography.csv -o /tmp/test.csv
  # Geography test with unsafe fixes
  - poetry run csv-metadata-quality -i data/test-geography.csv -o /tmp/test.csv -u
  # Test with experimental checks
  - poetry run csv-metadata-quality -i data/test.csv -o /tmp/test.csv -e
  # Test with AGROVOC validation
  - poetry run csv-metadata-quality -i data/test.csv -o /tmp/test.csv --agrovoc-fields dcterms.subject
  # Test with AGROVOC validation (and dropping invalid)
  - poetry run csv-metadata-quality -i data/test.csv -o /tmp/test.csv --agrovoc-fields dcterms.subject -d

---
kind: pipeline
type: docker
name: python310

steps:
- name: test
  image: python:3.10-slim
  commands:
  - id
  - python -V
  - apt update && apt install -y gcc g++ libicu-dev pkg-config git
  - python -m pip install poetry
  - poetry install
  - poetry run pytest
  # Basic test
  - poetry run csv-metadata-quality -i data/test.csv -o /tmp/test.csv
  # Basic test with unsafe fixes
  - poetry run csv-metadata-quality -i data/test.csv -o /tmp/test.csv -u
  # Geography test
  - poetry run csv-metadata-quality -i data/test-geography.csv -o /tmp/test.csv
  # Geography test with unsafe fixes
  - poetry run csv-metadata-quality -i data/test-geography.csv -o /tmp/test.csv -u
  # Test with experimental checks
  - poetry run csv-metadata-quality -i data/test.csv -o /tmp/test.csv -e
  # Test with AGROVOC validation
  - poetry run csv-metadata-quality -i data/test.csv -o /tmp/test.csv --agrovoc-fields dcterms.subject
  # Test with AGROVOC validation (and dropping invalid)
  - poetry run csv-metadata-quality -i data/test.csv -o /tmp/test.csv --agrovoc-fields dcterms.subject -d

---
kind: pipeline
type: docker
name: python39

steps:
- name: test
  image: python:3.9-slim
  commands:
  - id
  - python -V
  - apt update && apt install -y gcc g++ libicu-dev pkg-config git
  - python -m pip install poetry
  - poetry install
  - poetry run pytest
  # Basic test
  - poetry run csv-metadata-quality -i data/test.csv -o /tmp/test.csv
  # Basic test with unsafe fixes
  - poetry run csv-metadata-quality -i data/test.csv -o /tmp/test.csv -u
  # Geography test
  - poetry run csv-metadata-quality -i data/test-geography.csv -o /tmp/test.csv
  # Geography test with unsafe fixes
  - poetry run csv-metadata-quality -i data/test-geography.csv -o /tmp/test.csv -u
  # Test with experimental checks
  - poetry run csv-metadata-quality -i data/test.csv -o /tmp/test.csv -e
  # Test with AGROVOC validation
  - poetry run csv-metadata-quality -i data/test.csv -o /tmp/test.csv --agrovoc-fields dcterms.subject
  # Test with AGROVOC validation (and dropping invalid)
  - poetry run csv-metadata-quality -i data/test.csv -o /tmp/test.csv --agrovoc-fields dcterms.subject -d

# vim: ts=2 sw=2 et
