os: linux
arch: arm64-graviton2
dist: focal
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
jobs:
  allow_failures:
    - python: "nightly"
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
script: pytest

# vim: ts=2 sw=2 et
