dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
jobs:
  allow_failures:
    - python: "3.8-dev"
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
script: pytest

# vim: ts=2 sw=2 et
