[tool.poetry]
name = "csv-metadata-quality"
version = "0.6.1"
description="A simple, but opinionated CSV quality checking and fixing pipeline for CSVs in the DSpace ecosystem."
authors = ["Alan Orth <alan.orth@gmail.com>"]
license="GPL-3.0-only"
repository = "https://github.com/ilri/csv-metadata-quality"
homepage = "https://github.com/ilri/csv-metadata-quality"

[tool.poetry.scripts]
csv-metadata-quality = 'csv_metadata_quality.__main__:main'

[tool.poetry.dependencies]
python = "^3.9"
pandas = {version = "^2.0.2", extras = ["feather", "performance"]}
python-stdnum = "^1.18"
requests = "^2.28.2"
requests-cache = "^1.0.0"
colorama = "^0.4.6"
ftfy = "^6.1.1"
country-converter = "~1.1.0"
pycountry = "^23.12.7"
py3langid = "^0.2.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
flake8 = "^7.0.0"
pytest-clarity = "^1.0.1"
black = "^24.0.0"
isort = "^5.12.0"
csvkit = "^1.1.0"
ipython = "^8.10.0"
fixit = "^2.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.isort]
profile = "black"
line_length=88
