[tool.poetry]
name = "csv-metadata-quality"
version = "0.6.0-dev"
description="A simple, but opinionated CSV quality checking and fixing pipeline for CSVs in the DSpace ecosystem."
authors = ["Alan Orth <alan.orth@gmail.com>"]
license="GPL-3.0-only"
repository = "https://github.com/ilri/csv-metadata-quality"
homepage = "https://github.com/ilri/csv-metadata-quality"

[tool.poetry.scripts]
csv-metadata-quality = 'csv_metadata_quality.__main__:main'

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.4.0"
python-stdnum = "^1.13"
requests = "^2.28.1"
requests-cache = "^0.9.6"
pycountry = "^22.3.5"
langid = "^1.1.6"
colorama = "^0.4.5"
spdx-license-list = "^0.5.2"
ftfy = "^6.1.1"
country-converter = "^0.7.7"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
flake8 = "^5.0.4"
pytest-clarity = "^1.0.1"
black = "^22.8.0"
isort = "^5.10.1"
csvkit = "^1.0.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
