[tool.poetry]
name = "csv-metadata-quality"
version = "0.6.0-dev"
description="A simple, but opinionated CSV quality checking and fixing pipeline for CSVs in the DSpace ecosystem."
authors = ["Alan Orth <alan.orth@gmail.com>"]
license="GPL-3.0-only"
repository = "https://github.com/ilri/csv-metadata-quality"
homepage = "https://github.com/ilri/csv-metadata-quality"

[tool.poetry.scripts]
csv-metadata-quality = 'csv_metadata_quality.__main__:main'

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.4.0"
python-stdnum = "^1.13"
xlrd = "^1.2.0"
requests = "^2.27.1"
requests-cache = "^0.9.1"
pycountry = "^22.1.10"
langid = "^1.1.6"
colorama = "^0.4.4"
spdx-license-list = "^0.5.2"
ftfy = "^6.0"
SQLAlchemy = ">=1.3.3,<1.4.23"
country-converter = "^0.7.4"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"
flake8 = "^4.0.1"
pytest-clarity = "^1.0.1"
black = "^22.1.0"
isort = "^5.5.4"
csvkit = "^1.0.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
