# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Install rye
      uses: eifinger/setup-rye@v4
      with:
        version: 'latest'
    - run: rye sync
    - name: Lint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        rye lint
    - name: Test with pytest
      run: rye test
    - name: Test CLI
      run: |
        # Basic test
        rye run csv-metadata-quality -i data/test.csv -o /tmp/test.csv
        # Test with unsafe fixes
        rye run csv-metadata-quality -i data/test.csv -o /tmp/test.csv -u
        # Test with experimental checks
        rye run csv-metadata-quality -i data/test.csv -o /tmp/test.csv -e
        # Test with AGROVOC validation
        rye run csv-metadata-quality -i data/test.csv -o /tmp/test.csv --agrovoc-fields dcterms.subject
        # Test with AGROVOC validation (and dropping invalid)
        rye run csv-metadata-quality -i data/test.csv -o /tmp/test.csv --agrovoc-fields dcterms.subject -d
